name: Changed file contents from PR containing substring
description: Checks if the file contents from a PR contains a given substring
author: johnforeland

inputs:
    substring:
        description: 'Substring to check changed files with'
        required: true

outputs:
    allFilesContainsSubstring:
        description: return `true` if all changed file contents contains substring
    oneOrMoreFilesContainsSubstring:
        description: return `true` if one or more changed file contents contains substring

branding:
    icon: bar-chart-2
    color: orange

runs:
    using: 'node12'
    main: 'index.js'
